#!/bin/bash

print_help()
{
  error "usage: $(basename $BASH_SOURCE) <dataset> <regid> <cfgid> <tgtid> [<chn>]"
}

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$etcdir" ] || error "etc/settings.sh: etcdir not set"
[ -n "$setdir" ] || error "etc/settings.sh: setdir not set"
[ -n "$vardir" ] || error "etc/settings.sh: vardir not set"

# change to top-level directory
run cd "$topdir"

# evaluation dataset
dataset="$1"; shift
[ -n "$dataset" ] || print_help
. "$setdir/$dataset.sh"
[ ${#chns[@]}   -gt 0 ] || error "$setdir/$dataset.sh: chns not set"
[ ${#imgids[@]} -gt 0 ] || error "$setdir/$dataset.sh: imgids not set"
[ ${#srcids[@]} -gt 0 ] || srcids=("${imgids[@]}")

# registration method
regid="$1"; shift
[ -n "$regid" ] || print_help

# parameter set
cfgid="$1"; shift
[ -n "$cfgid" ] || print_help

# target image
tgtid="$1"; shift
[ -n "$tgtid" ] || print_help

# reference image
chn="$1"; shift
[ -n "$chn" ] || chn="${chns[0]}"
[ -n "$chn" ] || error "First chns entry invalid, specify chn argument"

# background value
bgvalue="$(get_bgvalue "$chn")"
if [ -n "$bgvalue" ]; then
  padding="-padding $bgvalue"
else
  padding=''
fi

# evaluate Jacobian determinants and print table
dofdir="$vardir/$dataset/$regid/$cfgid/dof"
imgdir="$vardir/$dataset/$regid/$cfgid/out/$chn"

echo "srcid,n,pct"
for srcid in "${srcids[@]}"; do
  if [ -f "$dofdir/$tgtid-$srcid.dof.gz" ]; then
    info=($("$mirtk" evaluate-jacobian "$imgdir/$srcid-$tgtid.nii.gz" "$dofdir/$tgtid-$srcid.dof.gz" $padding | grep 'Number of voxels with negative Jacobian determinant' | cut -d= -f2))
    if [ ${#info[@]} -eq 0 ]; then
      echo "$srcid,0,0"
    elif [ ${#info[@]} -eq 2 ]; then
      echo "$srcid,${info[0]},${info[1]:1:-2}"
    else
      error "Failed to determine no. of negative Jacobian determinants of '$dofdir/$tgtid-$srcid.dof.gz'"
    fi
  else
    error "Missing: $dofdir/$tgtid-$srcid.dof.gz"
  fi
done
