#!/bin/bash

## Generate command-line arguments for elastix using 'Full' ImageSampler
regid="$(basename "$BASH_SOURCE")"

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$cfgdir" ] || error "etc/settings.sh: cfgdir not set"

# change to top-level directory
run cd "$topdir"

# create output directory
makedir "$cfgdir"

# initial/constant parameter values
interp='Linear'
pyramid='Recursive'
optim='ConjugateGradient'
cgtype='PolakRibiere'
sim='NormalizedMutualInformation'
bins=64
levels=4
iters=500
steps=20
step=0.5
ds=2.5
be=0.005

# auxiliary function to append row with parameter values
# Attention: Always ensure that header and order of values is consistent!
i=0
parcsv="$cfgdir/$regid.csv"
echo "cfgid,interp,pyramid,optim,cgtype,sim,bins,levels,iters,steps,step,ds,be" > "$parcsv"

append_row()
{
  let i++
  local cfgid=$(printf %04d $i)
  echo "$cfgid,$interp,$pyramid,$optim,$cgtype,$sim,$bins,$levels,$iters,$steps,$step,$ds,$be" >> "$parcsv"
}

# initial parameter exploration
for step in 0.5 1.0; do
for bins in 32 64; do
for ds in 2.5 5.0; do
for be in 0 0.00001 0.0001 0.0005 0.001 0.005 0.01 0.05; do
  append_row
done; done; done; done
