#!/bin/bash

## Generate HTCondor job description file for MIRTK 'register' command

print_help()
{
  echo "usage: $(basename $BASH_SOURCE) <dataset> <regid> [<cfgid>...]" 1>&2
  exit 1
}

# arguments
dataset="$1"; shift
regid="$1"; shift

[ -n "$dataset" -a -n "$regid" ] || print_help

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$etcdir" ] || error "etc/settings.sh: etcdir not set"
[ -n "$setdir" ] || error "etc/settings.sh: setdir not set"
[ -n "$cfgdir" ] || error "etc/settings.sh: cfgdir not set"
[ -n "$vardir" ] || error "etc/settings.sh: vardir not set"
[ -n "$mirtk"  ] || error "etc/settings.sh: mirtk not set"

# change to top-level directory
run cd "$topdir"

# evaluation dataset
. "$setdir/$dataset.sh" || exit 1
[ ${#chns[@]}   -gt 0 ] || error "$setdir/$dataset.sh: chns not set"
[ ${#imgids[@]} -gt 0 ] || error "$setdir/$dataset.sh: imgids not set"
[ ${#tgtids[@]} -gt 0 ] || tgtids=("${imgids[@]}")
[ ${#srcids[@]} -gt 0 ] || srcids=("${imgids[@]}")

# registration method
issym="$(is_sym $regid)"
isic="$(is_ic $regid)"

# IDs of parameter sets
cfgids=("$@")
[ ${#cfgids} -gt 0 ] || cfgids=($(get_cfgids "$dataset" "$regid"))
[ ${#cfgids} -gt 0 ] || error "etc/settings.sh: get_cfgids is empty for $regid"

# dataset and registration specific parameters
if [ -f "$cfgdir/$dataset/$regid.csv" ]; then
  regcsv="$cfgdir/$dataset/$regid.csv"
  config="$(cat "$cfgdir/$dataset/$regid.txt")"
  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$dataset/$regid.txt"
elif [ -f "$cfgdir/$regid.csv" ]; then
  regcsv="$cfgdir/$regid.csv"
  config="$(cat "$cfgdir/$regid.txt")"
  [ -n "$config" ] || error "Missing configuration template file: $cfgdir/$regid.txt"
else
  error "Missing $regid.csv parameters file in $cfgdir[/$dataset]"
fi
paropt=($(head -n1 "$regcsv" | tr , '\n'))

#                   Energy function =
energy_indentation="                "

# generate job description for each configuration
regdir="$vardir/$dataset/$regid"
imgdir="$vardir/$dataset/affine/crp"
dofin='Id'
imgsuf=".nii.gz"

for cfgid in "${cfgids[@]}"; do

  echo "Write HTCondor job description for MIRTK register configuration $cfgid"

  # paths
  jobdir="$regdir/$cfgid/bin"
  dofdir="$regdir/$cfgid/dof"
  logdir="$regdir/$cfgid/log/register"
  pardir="$regdir/$cfgid/etc"

  # extract parameter values from CSV file
  if [ ${BASH_VERSION/.*} -lt 4 ]; then
    parval=()
    while IFS='\n' read line; do
      parval=("${parval[@]}" "$line")
    done < <(egrep "^$cfgid," "$regcsv" | tr , '\n')
  else
    readarray -t parval < <(egrep "^$cfgid," "$regcsv" | tr , '\n')
  fi
  [ -n "$parval" ] || error "$regcsv: Missing row '$cfgid,...'"
  [ ${#parval[@]} -eq ${#paropt[@]} ] || error "$regcsv: Expected ${#paropt[@]} columns for cfgid=$cfgid, got ${#parval[@]}"

  # substitute values in template configuration
  c=0
  usemsk=false
  usepad=true
  interp='Linear'
  parcfg="${config}"
  while [ $c -lt ${#paropt[@]} ]; do
    arg="${parval[c]}"
    case "${paropt[c]}" in
      allsym)
        allsym="$arg"
        ;;
      usemsk)
        usemsk="$arg"
        ;;
      usepad)
        usepad="$arg"
        ;;
      interp)
        interp="$arg"
        ;;
      *)
        parcfg="${parcfg//<${paropt[c]}>/$arg}"
        ;;
    esac
    let c++
  done

  # interpolation mode
  if [ "$usepad" = true ]; then
    interp="$interp with padding"
  fi
  parcfg="${parcfg//<interp>/$interp}"
  parcfg="${parcfg//<usepad>/$usepad}"

  # assemble data terms of energy function
  m=0
  n=0
  bgpars=''
  energy=''
  mskdir=''
  for chn in "${chns[@]}"; do
    [ -z "$energy" ] || energy="${energy}...\n${energy_indentation}+ "
    if [ "$(is_seg "$chn")" = true ] || [ "$(is_prob "$chn")" = true ]; then
      term="SSD"
    else
      term="SIM"
    fi
    let m++
    let t=$n+1
    let s=$n+2
    if [ "$issym" = true ]; then
      energy="${energy}${term}[Dissimilarity $m](I($t) o T^-0.5, I($s) o T^0.5)"
    elif [ "$isic" = true ]; then
      energy="${energy}${term}[Dissimilarity ${m}a](I($t) o T^-1, I($s))"
      energy="${energy}${term}[Dissimilarity ${m}b](I($t), I($s) o T)"
    else
      energy="${energy}${term}[Dissimilarity $m](I($t), I($s) o T)"
    fi
    bgvalue="$(get_bgvalue "$chn")"
    if [ -n "$bgvalue" ]; then
      if [ "$(is_mask "$bgvalue")" = true ]; then
        if [ "$usemsk" = true ]; then
          mskdir="$vardir/$dataset/affine/crp/$bgvalue"
        fi
        bgvalue="$(get_padvalue "$bgvalue")"
        [ -n "$bgvalue" ] || bgvalue=0
      elif [ "$usemsk" = true -a -z "$mskdir" ]; then
        mskdir="$imgdir/$chn-msk"
        makedir "$mskdir"
        for tgtid in "${tgtids[@]}"; do
          mskimg="$mskdir/$tgtid$imgsuf"
          [ ! -f "$mskimg" ] || continue
          run "$mirtk" calculate-element-wise "$imgdir/$chn/$tgtid$imgsuf" -mask "$bgvalue" -set 1 -pad 0 -o "$mskimg" binary
        done
      fi
      bgpars="${bgpars}\nBackground value of image $t = $bgvalue"
      bgpars="${bgpars}\nBackground value of image $s = $bgvalue"
    fi
    n=$s
  done
  energy="${energy}...\n${energy_indentation}+ 0 BE[Bending energy](T)"
  energy="${energy}...\n${energy_indentation}+ 0 TP[Topology preservation](T)"
  energy="${energy}...\n${energy_indentation}+ 0 VP[Volume preservation](T)"
  energy="${energy}...\n${energy_indentation}+ 0 LogJac[LogJac penalty](T)"
  energy="${energy}...\n${energy_indentation}+ 0 NegJac[NegJac penalty](T)"

  # make directories
  makedir "$pardir"
  makedir "$dofdir"
  makedir "$logdir"
  makedir "$jobdir"

  # write configuration to file
  parin="$pardir/register.cfg"
  echo -e "Energy function = $energy\n$bgpars\n\n$parcfg" > "$parin"

  # write job description
  jobdsc="$jobdir/register.condor"
  if [ $update = true ] || [ ! -f "$jobdsc" ]; then
    echo "Update: $jobdsc"
    cat > "$jobdsc" <<EOF_HEADER
universe     = vanilla
executable   = $topdir/$libdir/tools/measure-runtime
requirements = $condor_requirements
environment  = "$condor_environment"
getenv       = $condor_getenv
initialdir   = $topdir

EOF_HEADER
    for tgtid in "${tgtids[@]}"; do
    for srcid in "${srcids[@]}"; do
      [ $tgtid != $srcid ] || continue
      [ $allsym = true ] || [ $issym != true ] || [[ $tgtid < $srcid ]] || continue
      dofout="$dofdir/$tgtid-$srcid.dof.gz"
      [ $force = true ] || [ ! -f "$dofout" ] || continue
      images=()
      for chn in "${chns[@]}"; do
        imgpre="$chn/"
        bgvalue="$(get_bgvalue "$chn")"
        images=("${images[@]}" -image "'$imgdir/$imgpre$tgtid$imgsuf'" "'$imgdir/$imgpre$srcid$imgsuf'")      
      done
      mask=
      if [ -n "$mskdir" ]; then
        mask="-mask '$mskdir/$tgtid$imgsuf'"
      fi
      cat >> "$jobdsc" <<EOF_QUEUE
arguments = "'$mirtk' register ${images[@]} $mask -parin '$parin' -dofin '$dofin' -dofout '$dofout' -threads $threads"
error     = $logdir/$tgtid-$srcid.err
output    = $logdir/$tgtid-$srcid.out
log       = $logdir/$tgtid-$srcid.log
queue

EOF_QUEUE
    done; done
  else
    echo "Exists: $jobdsc"
  fi
done
