#!/bin/bash

## Generate HTCondor job description file to apply foreground
## masks and replace unmasked values by a constant background.
##
## This is done for tools such as IRTK and MIRTK where brain
## extraction masks are usually applied beforehand instead
## of given as separate input. For tools which take separate
## mask images as input, use these options instead.
##
## Execute these jobs after the affine alignment and transformation
## of the images to the comman affine reference space.

print_help()
{
  echo "usage: $(basename $BASH_SOURCE) <dataset>" 1>&2
  exit 1
}

# arguments
dataset="$1"; shift

[ -n "$dataset" ] || print_help

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$etcdir" ] || error "etc/settings.sh: etcdir not set"
[ -n "$setdir" ] || error "etc/settings.sh: setdir not set"
[ -n "$vardir" ] || error "etc/settings.sh: vardir not set"
[ -n "$mirtk"  ] || error "etc/settings.sh: mirtk not set"
[ ${mirtk:0:1} = / ] || mirtk="$topdir/$mirtk"

# change to top-level directory
run cd "$topdir"

# evaluation dataset
. "$setdir/$dataset.sh" || exit 1
[ ${#chns[@]}   -gt 0 ] || error "$setdir/$dataset.sh: chns not set"
[ ${#imgids[@]} -gt 0 ] || error "$setdir/$dataset.sh: imgids not set"

# paths
regid='affine'
regdir="$vardir/$dataset/$regid"
imgdir="$regdir/out"
outdir="$regdir/pad"
jobdir="$regdir/bin"
logdir="$regdir/log/apply-image-masks"
imgsuf=".nii.gz"

# create job description
jobdsc="$jobdir/apply-image-masks.condor"
if [ $update = true ] || [ ! -f "$jobdsc" ]; then
  echo "Update: $jobdsc"

  makedir "$jobdir"
  makedir "$logdir"
  makedir "$outdir"

  cat > "$jobdsc" <<EOF_HEADER
universe   = vanilla
executable = $mirtk
initialdir = $topdir

EOF_HEADER

  for chn in "${chns[@]}"; do
    msk=$(get_bgvalue "$chn")
    if [ -n "$msk" -a $(is_mask "$msk") = true ]; then
      makedir "$outdir/$chn"
      pad=$(get_padvalue "$chn")
      [ -n "$pad" ] || pad=0
      for imgid in "${imgids[@]}"; do
        outimg="$outdir/$chn/$imgid$imgsuf"
        [ $force = true ] || [ ! -f "$outimg" ] || continue
        cat >> "$jobdsc" <<EOF_JOB
arguments = "calculate-element-wise '$imgdir/$chn/$imgid$imgsuf' -mask '$imgdir/$msk/$imgid$imgsuf' -pad '$pad' -out '$outimg' -threads $threads"
error     = $logdir/$imgid.err
output    = $logdir/$imgid.out
log       = $logdir/$imgid.log
queue

EOF_JOB
      done
    else
      makedir "$outdir/$chn"
      reldir="$(relpath "$imgdir/$chn" "$outdir/$chn")"
      for imgid in "${imgids[@]}"; do
        if [ ! -f "$outdir/$chn/$imgid$imgsuf" ]; then
          run ln -s "$reldir/$imgid$imgsuf" "$outdir/$chn/$imgid$imgsuf"
        fi
      done
    fi
  done
else
  echo "Exists: $jobdsc"
fi
