#!/bin/bash

## Auxiliary script to evaluate overlap to local file and copy result to output file

. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir"   ] || error "etc/settings.sh: topdir not set"
[ -n "$mirtk"    ] || error "etc/settings.sh: mirtk executable path not set"

[ ${mirtk:0:1} = / ] || mirtk="$topdir/$mirtk"

args=()
table=

while [ $# -gt 0 ]; do
  case "$1" in
    -table)
      table="$2"
      shift; ;;
    *)
      args=("${args[@]}" "$1")
      ;;
  esac
  shift
done

if [ -z "$table" ]; then
  error "Missing -table option argument"
fi

tmp="$(mktemp)"
[ $? -eq 0 -a -n "$tmp" ] || error "Failed to create temporary file"

"$mirtk" evaluate-overlap "${args[@]}" -table "$tmp" && cp "$tmp" "$table"
if [ $? -ne 0 -a -n "$tmp" ]; then
  rm -f "$tmp"
  exit 1
fi
