#!/bin/bash

## Auxiliary script to create hard segmentations for the ALBERTs dataset
## with separate cortical and non-cortical labels using the cGM prior
## probability maps of the Draw-EM atlas
##
## https://www.doc.ic.ac.uk/~am411/atlases-DrawEM.html

. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
. "$topdir/$setdir/alberts.sh" || exit 1

run cd "$imgdir"
mkdir -p labels || exit 1

for i in {1..20}; do
  i=$(printf %02d $i)
  if [ ! -f "labels/ALBERT_$i.nii.gz" ]; do
    echo "Separate cortical labels using cGM probabilities > 0.5 of ALBERT $i"
    run "$topdir/$mirtk" calculate-element-wise gm-posteriors-v3/ALBERT_$i.nii.gz -threshold 0.5 -set 1 -pad 0 -out _tmp.nii.gz
    run "$topdir/$mirtk" calculate-element-wise segmentations-v3/ALBERT_$i.nii.gz -label 5..16 20..40 -mask _tmp.nii.gz -add 100 -o labels/ALBERT_$i.nii.gz
    run rm -f _tmp.nii.gz
  done
done
