#!/bin/bash

## Print table with statistics of logarithm of Jacobian determinant values
##
## Non-positive values are excluded, and the number of excluded values given
## in table column 'nexcl'. The number of positive Jacobian determinant values
## is given by the column with header name 'n'.

print_help()
{
  echo "usage: $(basename $BASH_SOURCE) <dataset> <regid> <cfgid> <tgtid>" 1>&2
  exit 1
}

# arguments
dataset="$1"; shift
regid="$1"; shift
cfgid="$1"; shift
tgtid="$1"; shift
[ -n "$dataset" -a -n "$regid" -a -n "$cfgid" -a -n "$tgtid" ] || print_help

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$etcdir" ] || error "etc/settings.sh: etcdir not set"
[ -n "$setdir" ] || error "etc/settings.sh: setdir not set"
[ -n "$vardir" ] || error "etc/settings.sh: vardir not set"

# change to top-level directory
cd "$topdir" || exit 1

# evaluation dataset
. "$setdir/$dataset.sh" || exit 1
[ ${#imgids[@]} -gt 0 ] || error "$setdir/$dataset.sh: imgids not set"
[ ${#srcids[@]} -gt 0 ] || srcids=("${imgids[@]}")

# print table of Jacobian determinants statistics
jacdir="$vardir/$dataset/$regid/$cfgid/evl/dof/jac"
echo "srcid,mean,sdev,median,pct5,pct95,pct5_mean,pct95_mean,min,max,n,nexcl"
for srcid in "${srcids[@]}"; do
  [ $srcid != $tgtid ] || continue
  jacimg="$jacdir/$tgtid-$srcid.nii.gz"
  if [ -f "$jacimg" ]; then
    echo "$srcid,$("$mirtk" calculate-element-wise "$jacimg" \
                        -threshold-le 0 -log -mean -sigma -median -pct 5 -pct 95 \
                        -lpctavg 5 -upctavg 95 -min -max \
                        -set 1 -sum -reset-mask \
                        -mask NaN -threshold-gt 0 -set 1 -sum \
                        -delim , -digits 9 -threads $threads)"
    [ $? -eq 0 ] || error "Failed: calculate-element-wise '$jacimg' [...]"
  else
    error "Missing: $jacimg"
  fi
done
