#!/bin/bash

## Print table with statistics of mean inverse consistency error (MICE)

print_help()
{
  echo "usage: $(basename $BASH_SOURCE) <dataset> <regid> <cfgid> [<tgtid>...]" 1>&2
  exit 1
}

# arguments
dataset="$1"; shift
regid="$1"; shift
cfgid="$1"; shift
[ -n "$dataset" -a -n "$regid" ] || print_help

# load settings and auxiliary functions
. "$(dirname "$BASH_SOURCE")/../../etc/settings.sh" || exit 1
[ -n "$topdir" ] || error "etc/settings.sh: topdir not set"
[ -n "$etcdir" ] || error "etc/settings.sh: etcdir not set"
[ -n "$setdir" ] || error "etc/settings.sh: setdir not set"
[ -n "$vardir" ] || error "etc/settings.sh: vardir not set"

# change to top-level directory
cd "$topdir" || exit 1

# evaluation dataset
. "$setdir/$dataset.sh" || exit 1
[ ${#imgids[@]} -gt 0 ] || error "$setdir/$dataset.sh: imgids not set"
[ ${#tgtids[@]} -gt 0 ] || tgtids=("${imgids[@]}")
[ $# -eq 0 ] || tgtids=("$@")

# print table of MICE statistics
regdir="$vardir/$dataset/$regid"
[ -z "$cfgid" ] || regdir="$regdir/$cfgid"
icedir="$regdir/evl/dof/mice"
echo "tgtid,mean,sdev,median,pct5,pct95,pct5_mean,pct95_mean,min,max,nzero,n"
for tgtid in ${tgtids[@]}; do
  iceimg="$icedir/$tgtid.nii.gz"
  if [ -f "$iceimg" ]; then
    echo "$tgtid,$("$mirtk" calculate-element-wise "$iceimg" \
                        -mean -sigma -median -pct 5 -pct 95 -lpctavg 5 -upctavg 95 -min -max \
                        -threshold-gt 0.1 -set 1 -sum -reset-mask -mask NaN -set 1 -sum \
                        -delim , -digits 9 -threads $threads)"
    [ $? -eq 0 ] || error "Failed: calculate-element-wise '$iceimg' [...]"
  else
    error "Missing: $iceimg"
  fi
done
